# Generated by Django 4.2 on 2023-05-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baits',
            name='user',
        ),
    ]
